config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users
  root 'groups#index'
  resources :users, only: [:index, :edit, :update, :destroy]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :comments, only: [:index, :create]

    namespace :api do
      resources :comments, only: :index, defaults: { format: 'json' }
    end
  end
  resources :syousais, only: [:index]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :comment, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :prefecture, optional: true
  validates :post_code, :city, :block_num, presence: true
  validates :first_name_kana, presence: true, format: { with: /[\p{katakana} ー－&&[^ -~｡-ﾟ]]+/,message: "全角カタカナのみが使用できます。" }
  validates :last_name_kana, presence: true, format: { with: /[\p{katakana} ー－&&[^ -~｡-ﾟ]]+/,message: "全角カタカナのみが使用できます。" }
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  has_many :comments
  validates :name, presence: true, uniqueness: true

  def show_last_comment
    if (last_comment = comments.last).present?
      if last_comment.comment?
        last_comment.comment
      else
        '画像が投稿されています'
      end
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/itemimage.rb
class Itemimage < ApplicationRecord
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many:destinations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :contents

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true, uniqueness: true
  # 半角英数字のみ許可_パスワード
  # VALID_PASSWORD_REGEX = /\A[a-z0-9]+\z/i
  # validates :encrypted_password, format: { with: VALID_PASSWORD_REGEX }
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_comment_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_comment_idよりも新しい(大きい)メッセージ達のみを取得
    @comments = group.comments.includes(:user).where("id > ?", last_comment_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_group

  def index
    @comment = Comment.new
    @comments = @group.comments.includes(:user)
  end

  def create
    @comment = @group.comments.new(comment_params)
    if @comment.save
      respond_to do |format|
        format.json
      end
    else
      @comments = @group.comments.includes(:user)
      flash.now[:alert] = 'メッセージを入力してください。'
      render :index
    end

    respond_to do |format|
      format.html { redirect_to group_comments_path, notice: "メッセージを送信しました" }
      format.json
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: 'グループを作成しました'
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_comments_path(@group), notice: 'グループを更新しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
  end
end

app/controllers/syousais_controller.rb
class SyousaisController < ApplicationController
  before_action :authenticate_user!
  def index
    @syousai = Item.new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return nil if params[:keyword] == ""
    @users = User.where(['username LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
    respond_to do |format|
      format.html
      format.json
    end
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    
  end

  private

  def user_params
    params.require(:user).permit(:username, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.haml
.comment-list{data: {comment: {id: comment.id}}}
  .comment-info
    %a.comment-info__name
      = comment.user.username
    %a.comment-info__date
      = comment.created_at.strftime("%Y年%m月%d日 %H時%M分")
  .comment
    - if comment.comment.present?
      %p.comment__info
        = comment.comment
    = image_tag comment.image.url, class: 'lower-comment__image' if comment.image.present?

app/views/comments/_main_chat.html.haml
.Chat-main

  .Chat-main__group-info
    .group-info
      .group-info__name
        = @group.name
      .group-info__member
        %a Member
        - @group.users.each do |user|
          = user.username
    .group-button
      %a= link_to "Edit", edit_group_path(@group), class: 'edit-button'

  .Chat-main__comment-list
    = render @comments

  .form
    = form_for [@group, @comment] do |f|
      .comment-form
        = f.text_field :comment, class: 'comment-form__comment', placeholder: 'type a comment'
        .comment-form__comment__icon
          = f.label :image, class: 'comment-form__comment__icon__content' do
            = icon('fas', 'image', class: 'icon')
            = f.file_field :image, class: 'hidden'
        = f.submit 'Send', class: 'comment-form__submit'

app/views/comments/_side_bar.html.haml
.Side-bar
  .Side-bar__user-name
    .top-items
      .top-items__name 
        = current_user.username
      .top-items__icons
        = link_to new_group_path do
          = icon('fa', 'edit',class: 'icon')
        %span<>
        = link_to edit_user_path(current_user) do
          = icon('fa', 'cog',class: 'icon')
        %span<>
        = link_to syousais_path(current_user) do
          = icon('fa', 'cog',class: 'icon')
        %span<>
  .Side-bar__group-list
    - current_user.groups.each do |group|
      .group
        = link_to group_comments_path(group) do
          .group__name
            = group.name
          .group__comment
            = group.show_last_comment

app/views/comments/index.html.haml
.wrapper
  = render "side_bar"
  = render "main_chat"

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |comment|
          %li= comment
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバーを追加"} チャットメンバーを追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{:placeholder => "追加したいユーザー名を入力してください", :type => "text"}/
      #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{:for => "chat_group_チャットメンバー"} チャットメンバー
    .chat-group-form__field--right

      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.username

        - group.users.each do |user|
          - if current_user.username != user.username
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.username 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: { group: @group }

app/views/groups/index.html.haml
.wrapper
  = render 'comments/side_bar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render partial: 'form', locals: { group: @group }

app/views/syousais/index.html.haml
= render 'home/header'
%div.nav
  %ul.listsLeft
    %li.listsLeft__item.listsLeft__item--first
      = link_to("/") do
        %a#catBtn
          カテゴリー
      %div.tree.displayNone
        %ul.categoryTree
          %li.categoryTree--item
            = link_to("/", id:"1") do
              レディース
          %li.categoryTree--item
            = link_to("/") do
              %a#2
                メンズ
          %li.categoryTree--item
            = link_to("/") do
              %a#3
                ベビー・キッズ
          %li.categoryTree--item
            = link_to("/") do
              %a#4
                インテリア・住まい・小物
          %li.categoryTree--item
            = link_to("/") do
              %a#5
                本・音楽・ゲーム
          %li.categoryTree--item
            = link_to("/") do
              %a#6
                おもちゃ・ホビー・グッズ
          %li.categoryTree--item
            = link_to("/") do
              %a#7
                コスメ・香水・美容
          %li.categoryTree--item
            = link_to("/") do
              %a#8
                家電・スマホ・カメラ
          %li.categoryTree--item
            = link_to("/") do
              %a#9
                スポーツ・レジャー
          %li.categoryTree--item
            = link_to("/") do
              %a#10
                ハンドメイド
          %li.categoryTree--item
            = link_to("/") do
              %a#11
                チケット
          %li.categoryTree--item
            = link_to("/") do
              %a#12
                自動車・オートバイ
          %li.categoryTree--item
            = link_to("/") do
              %a#13
                その他

%nav.breadCrumbs
  %ul
    %li
      = link_to("/") do
        %a
          FURIMA
    %li>
      %i.fa.fa-angle-right
    %li>
      = link_to("/") do
        %a
          ベビー・キッズ
    %li>
      %i.fa.fa-angle-right
    %li>
      = link_to("/") do
        %a
          ベビー服(男の子用)  ~95cm
    %li>
      %i.fa.fa-angle-right
    %li>
      = link_to("/") do
        %a
          アウター
    %li>
      %i.fa.fa-angle-right
    %li>
      %p
        ee
%div.main
  %div.showMain
    %div.contentLeftqq
    %div.contentRight
      %div.topContent
        %div.itemBox
          %h2.itemBox__name
            ee
          %div.itemBox__body
            %ul>
              %li>
                = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG"
                %ul>
                  %li>
                    = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/16/IMG_9072.JPG", size: "75x75"
                  %li>
                    = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/17/IMG_9069.JPG", size: "75x75"
          %div.itemBox__price
            %span
              ¥1000
            %div.itemBox__price-detail
            %span
              (税込)
            %span
              送料込み
        %div.itemDetail
          eee
          %div.table
            %table
              %tbody
                %tr
                  %th
                    出品者
                  %td
                    ss
                %tr
                  %th
                    カテゴリー
                  %td
                    = link_to("/") do
                      %a
                      ベビー・キッズ
                    %br
                    = link_to("/") do
                      %a
                        ベビー服(男の子用)  ~95cm
                    %br>
                    = link_to("/") do
                      %a
                        アウター
                %tr
                  %th
                    ブランド
                  %td
                %tr
                  %th
                    商品のサイズ
                  %td
                %tr
                  %th
                    商品の状態
                  %td
                    新品/未使用
                %tr
                  %th
                    配送料の負担
                  %td
                    送料込み（出品者負担）
                %tr
                  %th
                    発送元の地域
                  %td
                    = link_to("/") do
                      %a
                        北海道
                %tr
                  %th
                    発送日の目安
                  %td
                    1-2日で発送
          %div.optionalArea
            %ul>
              %li#likeBtn.optionalBtn.likeBtn
                %i.fa.fa-star
                お気に入り 0
            %ul.optional
              %li.optionalBtn
                = link_to("/") do
                  %a
                    %i.fa.fa-flag
                    不適切な商品の通報
        %div.commentBox
          %ul.commentContents
          = form_for @syousai,:url => {:action => :index} do |f|
            = f.text_field :name, placeholder: "キーワードから探す", class: "searchBox--input", id: "searchInput"
            = f.submit "検索", class: "searchBox--input"
            %p.noticeMsg
              相手のことを考え丁寧なコメントを心がけましょう。
              %br
              不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
              %i.fa.fa-comment
                コメントする
      %ul.links
        %li
          = link_to("/") do
            %a
              %i.fa.fa-angle-left
              %span
                前の商品
        %li
          = link_to("/") do
            %a
              %span
                後ろの商品
              %i.fa.fa-angle-right
      %div.relatedItems
        = link_to("/") do
          %a
            ベビー・キッズをもっと見る
        %div.productLists
          %div.productList
            = link_to("/products/3") do
              %a
                %figure.productList--img
                  = image_tag "https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/13/a007.png"
              %div.productList--body
                %h3.name
                  product3
                %div.details
                  %ul
                    %li
                      30000円
                    %li
                      %i.fa.fa-star.likeIcon
                        0
                  %p
                    (税込)
%aside.appBanner
  %div.inner
    %h2.inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.inner__text
      今すぐ無料ダウンロード！
    %div.inner__icon
      = link_to("/") do
        %a
          = image_tag "/assets/app-store-9c5e28e8f81bd9912e0ded2f78821e04778a1356c05dc7c7bf1e88614be37c34.svg", class: "linkIcon aBtn"
      = link_to("/") do
        %a
          = image_tag "/assets/google-play-469c63f1269e456307c4dde176b33cc3bbbbf142ac4d7369656010130149db1a.svg", class: "linkIcon gBtn"

%div.footer
  %ul.contents
    %li.content
      %h2.content__head
        FURIMAについて
      %ul
        %li
          = link_to("/") do
            %a
              会社概要（運営会社）
        %li
          = link_to("/") do
            %a
              プライバシーポリシー
        %li>
          = link_to("/") do
            %a
              FURIMA利用規約
        %li
          = link_to("/") do
            %a
              ポイントに関する特約
    %li.content
      %h2.content__head
        FURIMAを見る
      %ul
        %li
          = link_to("/") do
            %a
              カテゴリー一覧
        %li
          = link_to("/") do
            %a
              ブランド一覧
    %li.content
      %h2.content__head
        ヘルプ＆ガイド
      %ul
        %li
          = link_to("/") do
            %a
              FURIMAガイド
        %li
          = link_to("/") do
            %a
              FURIMAロゴ利用ガイドライン
        %li>
          = link_to("/") do
            %a
              お知らせ
  %div.footer__logo
    = link_to("/") do
      %a
        = image_tag "/assets/logo-white.png"
  %p
    © FURIMA
= link_to("/") do
  %a
    %div.purchaseBtn
      %span.purchaseBtn__text
        出品する
      = image_tag "/assets/icon_camera.png", class: "purchaseBtn__icon"

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :username
          .field-input
            = f.text_field :username, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'